### PR TITLE
Daniel wall #76 json

### PR DESCRIPTION
**Pull request by wall-daniel**
Finished everything with posting to the server. I'm fairly sure that I have gotten rid of most of the errors.

Note - some of the server stuff is using different tags for the value, e.g.: number of fuel scored is using 'position_x'

### CODE REVIEW

**Comment by ounsworth** [comment]
Hi Danny, I'm really happy that you're working on this :)

I'm a little uncomfortable putting a big feature like this straight into Master this close to the comp without the chance to test it as a group.

Umm, let's see, what can we do? Mainly I want to be confident that that it's been tested in lots of different ways. Would you be willing to post here a list of the different tests you've tried?

**Comment by wall-daniel** [comment]
So I have not merged into master since bag and tag night, so unless someone has merged without me knowing about it, posting to the server doesn't work correctly on master.

**Comment by ounsworth** [comment]
... so your argument is "I can't make it worse"? 

Question: at this point, are you only posting to the server, or are you also reading from the server and modifying the file on the phone?

**Comment by wall-daniel** [comment]
At this point on master I think it fails to post, but everything saves and read correctly on master. Now I have everything syncing and posting correctly, as far as I can tell.

**Comment by ounsworth** [comment]
Cool. I'm really really happy that you've gotten this working :) Yay!

Unfortunately, I won't have time myself between now and leaving to install it on my phone and really try to break it. What I'm worried about is that there's some weird edge case where it'll download from the server and wreck the local file.

I'll be happy to approve the pull request if you can convince me that you've tested lots of different things and there are no bugs.  ... so, what tests have you tried?

**Comment by wall-daniel** [comment]
So far I have tested scouting different matches while selecting every single option at least a few different times. When syncing everything loads onto the stats page, only problem is that in the test event there is a bunch of data that is messed up.

The only thing I can do that breaks the app is when I sync the files when I had just deleted the match data files it crashes, because the files can't be recreated fast enough. Though once you restart the app it works.

I'm going to see if anyone on discord wants to test my branch.

**Comment by ounsworth** [comment]
Ok, thanks for explaining what you've done. That all sounds pretty good.

We don't expect match data file to ever be deleted during actual use, right? And besides, there are a couple other places where you need to restart the app, like when you change events in the settings menu. So I guess it's "good enough".

I wonder if that could be easily fixed though. Where in MainActivity are you calling the db sync? I'm looking at [onResume() line 112](https://github.com/FRC2706/MCMergeManager/blob/DanielWall_%2376_JSON/Scouting/src/main/java/ca/team2706/scouting/mcmergemanager/gui/MainActivity.java#L112), which is where the file is loaded. Maybe you could block loading the file if stuff is downloading from the DB, or something. This is getting complicated, don't spend too long on this.

If Nathan doesn't find anything, and there's nothing else you want to test, I'll go ahead and approve this PR.

**Pull request merged**
